from typing import TypedDict, Annotated, List, Dict, Any
from langgraph.graph.message import add_messages

class TeachingState(TypedDict):
    """
    State for the Teaching Agent System.
    """
    # Messages in the conversation
    messages: Annotated[List[Any], add_messages]
    
    # Path to the uploaded training document
    document_path: str
    
    # Parsed document content (optional, or could be part of syllabus generation)
    document_content: str
    
    # List of modules/chapters generated by the Syllabus Agent
    # Structure: [{"title": "Chapter 1", "summary": "..."}]
    syllabus: List[Dict[str, str]]
    
    # Index of the current module being taught
    current_module_index: int
    
    # Generated detailed lesson plans/scripts for each module
    # Key: module title or index, Value: content string
    course_contents: Dict[str, str]
    
    # User's mastery of specific knowledge points (0-100)
    # Key: knowledge point, Value: score
    user_progress: Dict[str, int]
    
    # Retrieved context from the knowledge base for the current turn
    context_docs: List[str]
    
    # Flag to indicate if the current module is completed
    module_completed: bool
